### ISSUE TITLE
api/server/delete 是否需要彻底删除数据，而不只是标记为删除

### ISSUE THREAD

**Issue by guyskk** [NetEaseGame/git-webhook#16]
https://github.com/NetEaseGame/git-webhook/blob/master/tests/test_api.py#L50
https://github.com/NetEaseGame/git-webhook/blob/master/app/views/server.py#L85

**Comment by hustcc** [comment]
因为涉及到外键关系，所以如果删除的话，可能还需要删除相关的webhook配置，同事还有相关的hook_history.

**Comment by guyskk** [comment]
嗯，我暂时先不动它

**Comment by hustcc** [comment]
我觉目前最需要的：

1. websocket，自动刷新页面 hook 的状态，以及 history 页面数据自动更新（而不是手动刷新）。
2. Collaborators & teams 就是我之前说的观察者。

**Comment by guyskk** [comment]
这两个确实是很需要，但我更关注目前的可靠性(无Bug)，所以这两天都在完善测试。

websocket不知道你做了多少了，我还没看那个分支。
teams我觉得应该开个issue明确一下具体功能，也能让其他人也知道我们在做什么。

**Comment by hustcc** [comment]
嗯，你先把测试完善，后面在讨论~
