### ISSUE TITLE
怎样配置才能支持 GitLab 

### ISSUE THREAD

**Issue by zheng-ji** [NetEaseGame/git-webhook#17]
你好,　ReadMe　说能支持GitLab，但是我发现首页点击登陆，它跳转的是github. 
请问我需要怎样配置才能支持 GitLab 呢？

**Comment by hustcc** [comment]
你理解错了，支持 Github / GitLab / Gogs / GitOsc 的意思是：支持这些 git 服务的 webhook 来自动部署。

但是账号登陆只能是 github。Github 配置比较简单 ^_^

**Comment by zheng-ji** [comment]
好的。多谢解答。

**Comment by martin-huang** [comment]
所以是没有办法支持gitlab 吗有文档指示怎么配置吗

**Comment by hustcc** [comment]
登录不支持 gitlab。
