### ISSUE TITLE
hook shell 执行耗时

### ISSUE THREAD

**Issue by hustcc** [NetEaseGame/git-webhook#18]
目前没有记录 `hook shell 执行耗时`，个人使用过程中，觉得这个数据挺有用，下面会加入这个数据的记录。

大概会在 历史页面 添加一列，显示任务耗时，例如：`13.2s`, `2.3 min`, `1.2 h`

**Comment by guyskk** [comment]
@hustcc 
https://github.com/NetEaseGame/git-webhook/tree/issue18
我通过记录history状态最后更新时间实现的，感觉还可以改进。

**Comment by hustcc** [comment]
可以的，增加了数据库字段…这是开始数据库设计太烂了。

我们需要加 webapp 版本号了，对于已经在用的用户，不同版本号升级可能需要做一些处理，比如这个升级就需要添加一个数据库字段。

**Comment by hustcc** [comment]
时间显示上，不能直接显示秒（s），我用 [http://git.hust.cc/hrn/](http://git.hust.cc/hrn/) 这个格式化了一下，这个是我之前写的一个很小的 js 模块，专门做数字格式化的。
