### ISSUE TITLE
webapp 版本号

### ISSUE THREAD

**Issue by hustcc** [NetEaseGame/git-webhook#19]
1. 增加一个 版本号，在 web 页面的 footer 上显示。
2. 增加 CHANGELOG 文件，记录不同版本号之前修改；需要额外说明一下升级需要做的额外操作，比如数据库字段修改等，执行一些shell批处理等。

**Comment by guyskk** [comment]
手动维护数据库升级会不会太麻烦，特别是时间久了修改会越来越多。flask有个数据库迁移的插件，大部分情况都能自动迁移(有些比较复杂的改动需要自己编写迁移脚本)。
