### ISSUE TITLE
websocket

### ISSUE THREAD

**Issue by hustcc** [NetEaseGame/git-webhook#23]
主要用于以下几点：

1. 实时更新 webhook 的状态；
2. 实时新增 webhook history 数据；
3. 实时更新 webhook history 状态；

目前暂时考虑使用 socketIO。

**Comment by hustcc** [comment]
好的，我晚上把前端加进去。几个问题：

1. redis 做消息队列，应该可以个 celery 共享一个 db 吧？
2. 阻塞的问题感觉好像是 flask python 启动没有开启 thread 的感觉，但是按照 文档说明：

> Embedded Server
> The simplest deployment strategy is to have eventlet or gevent installed, and start the web server by calling socketio.run(app) as shown in examples above. This will run the application on the eventlet or gevent web servers, whichever is installed.

> Note that `socketio.run(app) runs a production ready server when eventlet or gevent are installed.` If neither of these are installed, then the application runs on Flask’s development web server, which is not appropriate for production use.

> Unfortunately this option is not available when using gevent with uWSGI. See the uWSGI section below for information on this option.

意思就是添加 socketio 之后，直接使用 python 运行，如果安装 eventlet 或者 gevent 的话，是可以直接在生产环境使用的。应该不存在 阻塞的问题，难道是 windows 原因？

**Comment by hustcc** [comment]
上面第二点已经解决：

```
socketio = SocketIO(app, async_mode='threading', message_queue=app.config['SOCKET_MESSAGE_QUEUE'])
```

**Comment by hustcc** [comment]
前段代码已经加了，后台代码做了一些修改，主要包括：

1. socket 重命名为 socketio，便于区分不是真正的 HTML5 websocket；
2. 添加 `async_mode='threading'`，是的直接 python 运行也可以正常工作；
3. 删除 socket.html 以及 相关测试代码；
4. config 文件中 `SOCKET_MESSAGE_QUEUE` 和 celery 共享一个 db；

**Comment by guyskk** [comment]
@hustcc 

- Gunicorn worker数量只能是1，这点得加到README中（如果没错的话我一会就加上）

  我重新看了一遍flask-socketio的文档，用了消息队列worker数量也只能是1

  > Gunicorn cannot be used with multiple workers because its load balancer algorithm does not support sticky sessions.
http://flask-socketio.readthedocs.io/en/latest/#using-multiple-workers

- 目前用户能通过socket收到所有webhook更新的消息，包括他原本没有权限的。
  可能要通过socketio的room机制才能解决这个问题。如果不解决也得在README里面说明。

**Comment by hustcc** [comment]
1. `gunicorn -w 1` worker 数量必须为 1，可以在 readme 中注明，如果使用 gunicorn 部署，需要指定 worker 数量为 1，贴上对应的官方文档。
2. 权限问题是个很严重的问题啊，我都没有想到这个。

**Comment by guyskk** [comment]
@hustcc 
- 第一点得再确认一下
- 要考虑collaborator吗

**Comment by hustcc** [comment]
第一点，我测试了，不支持多个 worker。

第二点，room 怎么划分好像还挺麻烦的；

- 使用 user.id 作为 room，用户只需要加入自己的 room 即可，但是发送消息需要发送到所有有权限的 room 中；
- 使用 webhook.id 作为 room，用户需要加入自己有权限的 room，但是发送的时候只需要发送当前 room 中；

以上两种方式，更加建议使用 第二种，第二种更加类似于聊天室的类比。

**Comment by guyskk** [comment]
第二种应该容易实现：

- 客户端获取webhook列表，加入所有room（webhook.id）
- 如果用户没有webhook.id的权限，拒绝加入
- emit消息时发送到相应的room（webhook.id）

**Comment by guyskk** [comment]
或者可以在连接时后端自动把用户加入所有有权限的room，这样前端无需修改。

**Comment by hustcc** [comment]
连接的时候，在后端加入有权限的 room 吧，毕竟是权限相关的，都是后台做，即使前端做了，后端还是需要验证的。

**Comment by guyskk** [comment]
权限问题已修复。

另一个问题，直接 `python run_webhook.py` 运行代码时，`ctrl+c` 不能停止运行。

**Comment by hustcc** [comment]
嗯，昨天好像确实遇到这个问题。应该也是 socketIO 引起的。

**Comment by hustcc** [comment]
简单修改了一下代码结构。已经更新到线上 DEMO 了。

**Comment by hustcc** [comment]
> 另一个问题，直接 python run_webhook.py 运行代码时，ctrl+c 不能停止运行。

参见 https://github.com/miguelgrinberg/Flask-SocketIO/issues/199 ，好像确实是一个问题，我是用supervisor管理进程，进程出现运行 supervisor restart webhook 的时候启动不起来，必须运行两次才能起来。

**Comment by hustcc** [comment]
需要使用 eventlet monkey_patch()
