### ISSUE TITLE
无法自动触发

### ISSUE THREAD

**Issue by TaylorHere** [NetEaseGame/git-webhook#27]
push事件并未成功触发webhook，
查看Github日志，push事件成功分发，
手动触发webhook，脚本成功执行。

Github里设置了webhook回调地址，但是没有填secret。

**Comment by hustcc** [comment]
不用填写 secret 的，在 github 的 webhook 中手动可以触发？但是 push 事件没有触发？

这个情况有点囧啊~

代码部署是怎么做的？

**Comment by wtli** [comment]
遇见同样的问题。。。怎么解决额

**Comment by TaylorHere** [comment]
具体怎么解决忘了，反正我弃了改用了一个叫SimpleDeployer的东西，这个项目在git oschina上面确实没法触发，但是github上面是可以用的。

发自我的 iPhone

**Comment by hustcc** [comment]
git oschina 是支持的，可能是但是 git osc 出了 bug，这个情况我遇到过一些。

**Comment by wtli** [comment]
谢谢各位~只是第一次测试成功了，后来移到生产上就不生效了。。醉了

**Comment by hustcc** [comment]
是不是生成环境不是外网，然后 osc 访问不到？

**Comment by wtli** [comment]
![image](https://cloud.githubusercontent.com/assets/19923589/25424310/8686d178-2a9a-11e7-91ff-d31d4738f593.png)
是有外网的
