### ISSUE TITLE
如何添加gitlab的repo？

### ISSUE THREAD

**Issue by kenee** [NetEaseGame/git-webhook#30]
在『Git Repository』填写完整的gitlab的项目地址并不能用啊

**Comment by hustcc** [comment]
截图看看，你是怎么样填写的？我们内网就是gitlab，可以用的…

**Comment by hustcc** [comment]
不是填写地址，而是填写名字，比如本项目名字是：`git-webhook`。

**Comment by kenee** [comment]
解决了，是我的理解错了，多谢。

**Comment by hustcc** [comment]
ok~
