### ISSUE TITLE
state没改变的问题

### ISSUE THREAD

**Issue by VectorHo** [NetEaseGame/git-webhook#33]
实际上已经执行完了shell的脚本，但是状态还是执行中；两次都执行完了

![image](https://cloud.githubusercontent.com/assets/7578264/21174960/fa2159f2-c21a-11e6-9fa0-1f1d1b86114b.png)

**Comment by hustcc** [comment]
你是使用 docker 安装的？
这个问题在内网开发中遇到过，解决办法在这里：[concurrency/eventlet.html](http://docs.celeryproject.org/en/latest/userguide/concurrency/eventlet.html)。

需要在启动的时候加入 -p 参数。

**Comment by VectorHo** [comment]
docker-compose启动的

**Comment by hustcc** [comment]
```
python manage.py --loglevel=info .... --detach -P eventlet
```
这样试试看。

**Comment by VectorHo** [comment]
@hustcc 启动还没发现其他问题

**Comment by guyskk** [comment]
报错有些奇怪，我待会再本地运行测试看是什么原因

**Comment by guyskk** [comment]
:( 本地测试一切正常
