### ISSUE TITLE
执行gitwebhook celery的时候redis报错

### ISSUE THREAD

**Issue by wtli** [NetEaseGame/git-webhook#38]
配置：
cat /root/.git-webhook/git_webhook_config.py
CELERY_BROKER_URL = 'redis://:redis_pwd@127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://:redis_pwd@127.0.0.1:6379/0'

SOCKET_MESSAGE_QUEUE = 'redis://:redis_pwd@127.0.0.1:6379/0'

/usr/lib/python2.7/site-packages/celery/platforms.py:812: RuntimeWarning: You are running the worker with superuser privileges, which is
absolutely not recommended!

Please specify a different user using the -u option.

[2017-04-12 13:45:14,890: ERROR/MainProcess] consumer: Cannot connect to redis://:**@127.0.0.1:6379/0: .
Trying again in 2.00 seconds...
我的redis服务是正常OK的。端口在监听

**Comment by hustcc** [comment]
git_webhook_config.py 中填写的 redis 密码是正确的吧？你们服务器的 redis 有配置密码，并且密码是 redis_pwd？

**Comment by hustcc** [comment]
如果不需要良好的 web gui 界面，建议可以使用：[webhookit](https://github.com/hustcc/webhookit)，配置和部署会简单很多，不需要依赖 redis。

**Comment by wtli** [comment]
非常感谢，设置密码为redis_pwd解决了。

**Comment by wtli** [comment]
又碰到一个新的问题：your_domain/github/callback.能给一个参考的例子吗？在Authorization callback URL的地方应该怎么设置呢？我尝试了很多种都登陆不了。比如：https://api.github.com/user?access_token=647ba66e780dae846309574c587b538787f01806

**Comment by hustcc** [comment]
比如你内网搭建，访问的地址为 http://10.xx.xxx.xx:18340。

那么你填写的地址就为 http://10.xx.xxx.xx:18340/github/callback

**Comment by wtli** [comment]
我要好好整理一下文档，多谢指点。

**Comment by wtli** [comment]
用gitwebhook runserver &方式退出终端之后，服务就不可用了。。。

**Comment by hustcc** [comment]
在前面加一个nohup，或者用其他的进程管理工具…
