### ISSUE TITLE
添加webhook之后，无法自动触发。手动点击可以成功

### ISSUE THREAD

**Issue by wtli** [NetEaseGame/git-webhook#39]

**Comment by wtli** [comment]
![image](https://cloud.githubusercontent.com/assets/19923589/25416600/2cffd7fe-2a71-11e7-9590-5ae7533ca4fd.png)

**Comment by wtli** [comment]
![image](https://cloud.githubusercontent.com/assets/19923589/25416626/5300fa5a-2a71-11e7-8484-51ee3c8ac53a.png)

**Comment by hustcc** [comment]
github 添加 webhook 的时候是不是没有选择 JSON 格式？

**Comment by wtli** [comment]
如何选择JSON格式？
http://XXX.XXX.XXX.XXX:18340/api/git-webhook/d091b0691ff3cafb0a0521b15ce9cdb2.json
还是http://XXX.XXX.XXX.XXX:18340/api/git-webhook/d091b0691ff3cafb0a0521b15ce9cdb2/trigger-ci.json

**Comment by hustcc** [comment]
在 github 的 webhooks 中添加的时候，可以选择请求参数的方式，是一个下拉框，可以选择 form/json 两种，你选择为 json 试试，我这里不能上传截图。

**Comment by wtli** [comment]
我这边用gitlab的，没有看到跟github里面那样的下拉框

**Comment by hustcc** [comment]
gitlab 应该没有问题，你是什么版本的 gitlab，不排除是版本问题。

**Comment by wtli** [comment]
GitLab 7.11.4，之前也是这个gitlab做的测试，可以使用，后来换台主机就不行了。先妥协手动触发吧，后面再看看。谢啦~

**Comment by hustcc** [comment]
你是阿里内部的？

**Comment by xingmolu** [comment]
我的也不行，手动点retry也不行，看了下日志，数据过来了。history也创建了，但是do the async task后就没有然后了，请问怎么调试啊，没有用过这个任务队列

**Comment by hustcc** [comment]
celery是否启动？

**Comment by xingmolu** [comment]
我直接运行的python runserver，celery是否启动不清楚？能告诉下怎么查看或者我明天在google下

**Comment by hustcc** [comment]
项目 readme 就有详细的启动方法。

**Comment by xingmolu** [comment]
@hustcc 嗯，谢谢。已经正常运行一周了

**Comment by fujinzhou** [comment]
请问gogs 如何添加webhook

**Comment by hustcc** [comment]
一样的，在 gogs 中的 webhook 设置页面！
