### ISSUE TITLE
有没有考虑过加上Ansible呢？

### ISSUE THREAD

**Issue by MrDreamerSang** [NetEaseGame/git-webhook#40]
感觉后端调ansible api去执行任务更灵活一点，可以批量执行任务，还可以添加一些常用的定制任务。。。

**Comment by hustcc** [comment]
这个可以自己在shell配置中去调用吗？

**Comment by MrDreamerSang** [comment]
ansible有python api，比shell好用多了

**Comment by hustcc** [comment]
确实是比 shell 好用，但是扩展上没有 shell 方便。如果可以支持 ansible，可能也需要支持其他 nodejs，go 等语言的~

使用 shell 脚本，可以在 shell 中定义自己任意的任务。

**Comment by MrDreamerSang** [comment]
我的意思是用ansible取代shell去执行任务，把你的自定制任务都放到ansible里面去跑，而且ansible有很多模块可以拿过来直接用，比写shell要方便多了
