### ISSUE TITLE
安装失败，心好累

### ISSUE THREAD

**Issue by SpringStudent** [NetEaseGame/git-webhook#51]
![image](https://user-images.githubusercontent.com/14833956/37704853-1645efae-2d35-11e8-887c-1d9f277fc03d.png)

**Comment by guyskk** [comment]
python-engineio 这个包需要 python 3.5 及以上版本才能用。我印象中 gitwebhook 是支持 python2.7 的，可以用 python3.6 或者 python2.7 再试试。

**Comment by SpringStudent** [comment]
![image](https://user-images.githubusercontent.com/14833956/38231921-68a8a3f6-3747-11e8-9ce9-a7baf235304a.png)

**Comment by SpringStudent** [comment]
想用用，弄不好。
