### ISSUE TITLE
关于发布为 pip 包，使得安装部署更加容易

### ISSUE THREAD

**Issue by guyskk** [NetEaseGame/git-webhook#8]
这个项目包含了一些前端代码，还有mysql和redis这两个依赖，所以封装到docker里面应该会更合适，这样还可以用docker-compose一键部署。

**Comment by guyskk** [comment]
Sorry，我遗漏了一点，在docker里面无法对宿主机进行操作。

**Comment by hustcc** [comment]
发布为pip或者npm都是不错的选择，类似sentry，sentry是发布为pip的。

**Comment by hustcc** [comment]
其实docker也不错，这个执行shell脚本的方式是使用ssh登录的方式，应该不受你所谓的因素影响。

**Comment by guyskk** [comment]
OK，我明天试试

**Comment by hustcc** [comment]
我也顺带学习学习😊

**Comment by guyskk** [comment]
@hustcc 代码是Python2的吗？我用Python3安装报错:
http://stackoverflow.com/questions/14087598/python-3-importerror-no-module-named-configparser

**Comment by hustcc** [comment]
是的，我们内网都是 2.7 版本，3.0 + 版本都没有测试过。

可能需要测试一下，然后把一些 api 和语法修改一下，应该修改的不多，我抽个空兼容一下 py3.

**Comment by guyskk** [comment]
@hustcc 
这是我用Docker部署的 http://purepage.org:18340/ 除了pull镜像的时候有点慢，没其他问题。

**Comment by hustcc** [comment]
已经支持 docker 安装。感谢 @guyskk 。
