### ISSUE TITLE
安装之前需要哪些依赖？

### ISSUE THREAD

**Issue by xuzongbao** [NetEaseGame/git-webhook#9]
我在执行第二步的时候就执行不下去了，抱歉，烦请解答一下

**Comment by hustcc** [comment]
直接按照指引安装依赖不行吗？

```sh
pip install -r requirements.txt
npm install
```

依赖在 requirements.txt 和 package.json 文件中都有写清楚的。

**Comment by xuzongbao** [comment]
直接按照指引安装不行。。。。。。。

**Comment by hustcc** [comment]
有什么错误可以贴一下吗？

**Comment by hustcc** [comment]
我在最新的一次提交中 https://github.com/NetEaseGame/git-webhook/commit/6ebc9bf7ebfe338cb6fdeacb5455d9eea490fc12 简化了安装步骤，不需要在安装js依赖了。

只需要运行 `pip install -r requirements.txt` 即可。

**Comment by xuzongbao** [comment]
root@iZ28i81rup1Z:/git-repo/webhook/git-webhook# pip install -r requirements.txt 
Downloading/unpacking Flask==0.11.1 (from -r requirements.txt (line 1))
  http://mirrors.aliyun.com/pypi/simple/Flask/0.11.1 uses an insecure transport scheme (http). Consider using https if mirrors.aliyun.com has it available
  http://mirrors.aliyun.com/pypi/simple/Flask/ uses an insecure transport scheme (http). Consider using https if mirrors.aliyun.com has it available
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB): 80kB downloaded
Downloading/unpacking Flask-SQLAlchemy==2.1 (from -r requirements.txt (line 2))
  http://mirrors.aliyun.com/pypi/simple/Flask-SQLAlchemy/2.1 uses an insecure transport scheme (http). Consider using https if mirrors.aliyun.com has it available
  http://mirrors.aliyun.com/pypi/simple/Flask-SQLAlchemy/ uses an insecure transport scheme (http). Consider using https if mirrors.aliyun.com has it available
  Downloading Flask-SQLAlchemy-2.1.tar.gz (95kB): 95kB downloaded
  Running setup.py (path:/tmp/pip_build_root/Flask-SQLAlchemy/setup.py) egg_info for package Flask-SQLAlchemy
    
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
Downloading/unpacking MySQL-python==1.2.5 (from -r requirements.txt (line 3))
  http://mirrors.aliyun.com/pypi/simple/MySQL-python/1.2.5 uses an insecure transport scheme (http). Consider using https if mirrors.aliyun.com has it available
  http://mirrors.aliyun.com/pypi/simple/MySQL-python/ uses an insecure transport scheme (http). Consider using https if mirrors.aliyun.com has it available
  Downloading MySQL-python-1.2.5.zip (108kB): 108kB downloaded
  Running setup.py (path:/tmp/pip_build_root/MySQL-python/setup.py) egg_info for package MySQL-python
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/MySQL-python/setup.py", line 17, in <module>

    metadata, options = get_config()

  File "setup_posix.py", line 43, in get_config

    libs = mysql_config("libs_r")

  File "setup_posix.py", line 25, in mysql_config

    raise EnvironmentError("%s not found" % (mysql_config.path,))

EnvironmentError: mysql_config not found

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/MySQL-python
Storing debug log for failure in /root/.pip/pip.log

**Comment by xuzongbao** [comment]
先只执行了：pip install -r requirements.txt
然后报错我就安装了js，也不行。
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected end of input
npm ERR! {"_id":"babel-eslint","_rev":"162-e9365ee64c3ebcb179f9fa708b2f1fa8","name":"babel-eslint","dist-tags":{"latest":"7.1.0","next":"6.0.0-beta.6","prev":"5.0.4"},"versions":{"1.0.0":{"name":"babel-eslint","version":"1.0.0","description":"","main":"index.js","repository":{"type":"git","url":"https://github.com/babel/babel-eslint.git"},"author":{"name":"Sebastian McKenzie","email":"sebmck@gmail.com"},"license":"MIT","bugs":{"url":"https://github.com/babel/babel-eslint/issues"},"homepage":"https://github.com/babel/babel-eslint","gitHead":"f6eac866dfb420c8ef2584dd03cb98ee4253e86e","_id":"babel-eslint@1.0.0","scripts":{},"_shasum":"4fb7392d199ccd74d438126879418e34e0240cc1","_from":".","_npmVersion":"2.6.0","_nodeVersion":"1.4.1","_npmUser":{"name":"sebmck","email":"sebmck@gmail.com"},"maintainers":[{"name":"sebmck","email":"sebmck@gmail.com"}],"dist":{"shasum":"4fb7392d199ccd74d438126879418e34e0240cc1","tarball":"https://registry.npmjs.org/babel-eslint/-/babel-eslint-1.0.0.tgz"},"directories":{}},"1.0.1":{"name":"babel-eslint","version":"1.0.1","description":"","main":"index.js","repository":{"type":"git","url":"https://github.com/babel/babel-eslint.git"},"dependencies":{"babel":"^4.6.0"},"author":{"name":"Sebastian McKenzie","email":"sebmck@gmail.com"},"license":"MIT","bugs":{"url":"https://github.com/babel/babel-eslint/issues"},"homepage":"https://github.com/babel/babel-eslint","gitHead":"f6eac866dfb420c8ef2584dd03cb98ee4253e86e","_id":"babel-eslint@1.0.1","scripts":{},"_shasum":"24361610bb91c740d778acbdaf056c6d0c965acb","_from":".","_npmVersion":"2.6.0","_nodeVersion":"1.4.1","_npmUser":{"name":"sebmck","email":"sebmck@gmail.com"},"maintainers":[{"name":"sebmck","email":"sebmck@gmail.com"}],"dist":{"shasum":"24361610bb91c740d778acbda

。。。。。。。。。。
ps://github.com/babel/babel-eslint/issues"
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-86-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /git-repo/webhook/git-webhook
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_eos
。。。。。。
。。。。。。
。。。。。
npm ERR! registry error parsing json
npm http 200 https://registry.npmjs.org/eslint
npm ERR! registry error parsing json
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /git-repo/webhook/git-webhook/npm-debug.log
npm ERR! not ok code 0

**Comment by hustcc** [comment]
`MySQL-python` 这个如果是在 windows 系统安装的话，需要自己下载编译好的exe安装包安装。

**Comment by hustcc** [comment]
javascript 依赖不用安装了。

**Comment by xuzongbao** [comment]
我是在阿里云linux服务器上操作的

**Comment by hustcc** [comment]
mysql安装没？如果没有安装可以使用sqlite…

项目的网站就是在阿里云。

**Comment by xuzongbao** [comment]
mysql貌似没有安装，那我安装一下sqlite试试

**Comment by hustcc** [comment]
嗯，config_example.py 中有一个 sqlite 的 data_url 示例，注意给数据库目录加上 `777` 权限哦~

**Comment by hustcc** [comment]
应该安装没有问题了，我关闭 issue，如果有问题，可以 reopen。

**Comment by xuzongbao** [comment]
额，这两天有点忙，还是没有解决。。。。。
